# Config file for Air
root = "."
temp_dir = "tmp"
[build]
  cmd = "go build -o tmp/main"
  bin = "tmp/main"
  full_bin = "./tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor", "node_modules"]
  delay = 1000
  exclude_file = ["_test.go"]
